// This file is automatically generated by aux/PWMSS_REGS.sh
#ifndef FILIPEBELO_PWMSS_H
#define FILIPEBELO_PWMSS_H

#include <stdint.h>
#include "pwmss_bitfields.h"

#define PWMSS_OFFSET_IDVER 0x0u
#define PWMSS_OFFSET_SYSCONFIG 0x4u
#define PWMSS_OFFSET_CLKCONFIG 0x8u
#define PWMSS_OFFSET_CLKSTATUS 0xCu

struct pwmss_regs_t {
	PWMSS_IDVER_reg_t IDVER;
	PWMSS_SYSCONFIG_reg_t SYSCONFIG;
	PWMSS_CLKCONFIG_reg_t CLKCONFIG;
	PWMSS_CLKSTATUS_reg_t CLKSTATUS;
};

#endif
