#! /bin/bash
# This table is on the reference manual
REGLIST="\
0h	REVID
4h	CR
10h	GER
1Ch	GNLR
20h	SISR
24h	SICR
28h	EISR
2Ch	EICR
34h	HIEISR
38h	HIDISR
80h	GPIR
200h	SRSR0
204h	SRSR1
280h	SECR0
284h	SECR1
300h	ESR0
304h	ERS1
380h	ECR0
384h	ECR1
400h	CMR0
404h	CMR1
408h	CMR2
40Ch	CMR3
410h	CMR4
414h	CMR5
418h	CMR6
41Ch	CMR7
420h	CMR8
424h	CMR9
428h	CMR10
42Ch	CMR11
430h	CMR12
434h	CMR13
438h	CMR14
43Ch	CMR15
800h	HMR0
804h	HMR1
808h	HMR2
900h	HIPIR0
904h	HIPIR1
908h	HIPIR2
90Ch	HIPIR3
910h	HIPIR4
914h	HIPIR5
918h	HIPIR6
91Ch	HIPIR7
920h	HIPIR8
924h	HIPIR9
D00h	SIPR0
D04h	SIPR1
D80h	SITR0
D84h	SITR1
1100h	HINLR0
1104h	HINLR1
1108h	HINLR2
110Ch	HINLR3
1110h	HINLR4
1114h	HINLR5
1118h	HINLR6
111Ch	HINLR7
1120h	HINLR8
1124h	HINLR9
1500h	HIER"

(
	echo "// This file is automatically generated by aux/INTC_REGS.sh"
	echo "#ifndef LHARTMANN_PRU_ICSS_INTC_H"
	echo "#define LHARTMANN_PRU_ICSS_INTC_H"
	echo ""
	echo "#include \"pru_icss_intc_bitfields.h\""
	echo ""
	
	echo "$REGLIST" | while read ADDR NAME; do
		echo "#define PRU_ICSS_INTC_OFFSET_$NAME 0x${ADDR%h}u"
	done
	echo ""
	
	POS=0
	echo "struct pru_icss_intc_regs_t {"
	echo "$REGLIST" | while read ADDR NAME; do
		OFF=$(( 0x${ADDR%h} ))
		if [[ $OFF != $POS ]]; then
			echo -e "\tuint8_t _rsvd_${POS}[$(( OFF-POS ))];"
		fi
		if grep -q "$NAME" < pru_icss_intc_bitfields.h; then
			echo -e "\tpru_icss_intc_${NAME}_reg_t $NAME;"
		else 
			echo -e "\tuint32_t $NAME;"
		fi
		POS=$((OFF+4));
	done
	echo "};"
	echo ""
	echo "#endif"
) > pru_icss_intc.h

# Test function code
(
	echo "// This file is automatically generated by aux/INTC_REGS.sh"
	echo "#ifndef LHARTMANN_PRU_ICSS_INTC_OFFSET_TEST_H"
	echo "#define LHARTMANN_PRU_ICSS_INTC_OFFSET_TEST_H"
	echo ""
	echo "#include \"pru.h\""
	echo ""
	echo '#define fail(XXX) { \'
	echo '	cerr << hex << "Failed offset for " #XXX ". Expected 0x" << PRU_ICSS_INTC_OFFSET_##XXX << ", got 0x" << ((uint8_t*)&intc. XXX - (uint8_t*)&intc) << "." << endl << dec; \'
	echo '}'

	echo "bool test_intc_offsets() {"
	echo -e "\tpru_icss_intc_regs_t intc;"
	echo -e "\t bool err = false;"
	echo "$REGLIST" | while read ADDR NAME; do
		echo -e "\tif ((uint8_t*)&intc.$NAME - (uint8_t*)&intc != PRU_ICSS_INTC_OFFSET_$NAME) {"
		echo -e "\t\tfail($NAME);"
		echo -e "\t\terr = true;"
		echo -e "\t}"
	done
	echo -e "\treturn err;"
	echo "}"
	echo ""
	echo "#endif"
) > pru_icss_intc_test.h
