#! /bin/bash
# This table is on the reference manual
REGLIST="\
0h	TSCTR	4
4h	CTRPHS	4
8h	CAP1	4
Ch	CAP2	4
10h	CAP3	4
14h	CAP4	4
28h	ECCTL1	2
2Ah	ECCTL2	2
2Ch	ECEINT	2
2Eh	ECFLG	2
30h	ECCLR	2
32h	ECFRC	2
5Ch	REVID	4"

(
	echo "// This file is automatically generated by aux/PWMSS_REGS.sh"
	echo "#ifndef FILIPEBELO_PWMSS_ECAP_H"
	echo "#define FILIPEBELO_PWMSS_ECAP_H"
	echo ""
	echo "#include \"PWMSS_ECAP_bitfields.h\""
	echo ""
	
	echo "$REGLIST" | while read ADDR NAME SIZE; do
		echo "#define PWMSS_ECAP_OFFSET_$NAME 0x${ADDR%h}u"
	done
	echo ""
	
	POS=0
	echo "struct pwmss_ecap_regs_t {"
	echo "$REGLIST" | while read ADDR NAME SIZE; do
		OFF=$(( 0x${ADDR%h} ))
		if [[ $OFF != $POS ]]; then
			echo -e "\tuint8_t _rsvd_${POS}[$(( OFF-POS ))];"
		fi
		if grep -q "$NAME" < PWMSS_ECAP_bitfields.h; then
			echo -e "\tPWMSS_ECAP_${NAME}_reg_t $NAME;"
		else 
			if   [ $SIZE -eq 4 ]; then
				echo -e "\tuint32_t $NAME;"
			elif [ $SIZE -eq 2 ]; then
				echo -e "\tuint16_t $NAME;"
			else
				echo "ERROR" >&2
				exit 1
			fi
		fi
		POS=$((OFF+$SIZE));
	done
	echo "};"
	echo ""
	echo "#endif"
) > pwmss_ecap.h

# Test function code
(
	echo "// This file is automatically generated by aux/PWMSS.sh"
	echo "#ifndef FILIPEBELO_PWMSS_ECAP_OFFSET_TEST_H"
	echo "#define FILIPEBELO_PWMSS_ECAP_OFFSET_TEST_H"
	echo ""
	echo "#include \"pwmss_ecap.h\""
	echo ""
	echo '#define fail(XXX) { \'
	echo '	cerr << hex << "Failed offset for " #XXX ". Expected 0x" << PWMSS_ECAP_OFFSET_##XXX << ", got 0x" << ((uint8_t*)&ecap. XXX - (uint8_t*)&ecap) << "." << endl << dec; \'
	echo '}'

	echo "bool test_tscadc_offsets() {"
	echo -e "\tpwmss_ecap_regs_t ecap;"
	echo -e "\t bool err = false;"
	echo "$REGLIST" | while read ADDR NAME SIZE; do
		echo -e "\tif ((uint8_t*)&ecap.$NAME - (uint8_t*)&ecap != PWMSS_OFFSET_$NAME) {"
		echo -e "\t\tfail($NAME);"
		echo -e "\t\terr = true;"
		echo -e "\t}"
	done
	echo -e "\treturn err;"
	echo "}"
	echo "#undef fail"
	echo "#endif"
) > pwmss_ecap_test.h
