#! /bin/bash
# This table is on the reference manual
REGLIST="\
0h	REVISION
10h	SYSCONFIG
24h	IRQSTATUS_RAW
28h	IRQSTATUS
2Ch	IRQENABLE_SET
30h	IRQENABLE_CLR
34h	IRQWAKEUP
38h	DMAENABLE_SET
3Ch	DMAENABLE_CLR
40h	CTRL
44h	ADCSTAT
48h	ADCRANGE
4Ch	ADC_CLKDIV
50h	ADC_MISC
54h	STEPENABLE
58h	IDLECONFIG
5Ch	TS_CHARGE_STEPCONFIG
60h	TS_CHARGE_DELAY
64h	STEPCONFIG1
68h	STEPDELAY1
6Ch	STEPCONFIG2
70h	STEPDELAY2
74h	STEPCONFIG3
78h	STEPDELAY3
7Ch	STEPCONFIG4
80h	STEPDELAY4
84h	STEPCONFIG5
88h	STEPDELAY5
8Ch	STEPCONFIG6
90h	STEPDELAY6
94h	STEPCONFIG7
98h	STEPDELAY7
9Ch	STEPCONFIG8
A0h	STEPDELAY8
A4h	STEPCONFIG9
A8h	STEPDELAY9
ACh	STEPCONFIG10
B0h	STEPDELAY10
B4h	STEPCONFIG11
B8h	STEPDELAY11
BCh	STEPCONFIG12
C0h	STEPDELAY12
C4h	STEPCONFIG13
C8h	STEPDELAY13
CCh	STEPCONFIG14
D0h	STEPDELAY14
D4h	STEPCONFIG15
D8h	STEPDELAY15
DCh	STEPCONFIG16
E0h	STEPDELAY16
E4h	FIFO0COUNT
E8h	FIFO0THRESHOLD
ECh	DMA0REQ
F0h	FIFO1COUNT
F4h	FIFO1THRESHOLD
F8h	DMA1REQ
100h	FIFO0DATA
200h	FIFO1DATA
"

(
	echo "// This file is automatically generated by aux/TSCADCSS_REGS.sh"
	echo "#ifndef KRHUAN_TSCADCSS_INTC_H"
	echo "#define KRHUAN_TSCADCSS_INTC_H"
	echo ""
	echo "#include \"tscadcss_bitfields.h\""
	echo ""
	
	echo "$REGLIST" | while read ADDR NAME; do
		echo "#define TSCADCSS_OFFSET_$NAME 0x${ADDR%h}u"
	done
	echo ""
	
	POS=0
	echo "struct tscadcss_regs_t {"
	echo "$REGLIST" | while read ADDR NAME; do
		OFF=$(( 0x${ADDR%h} ))
		if [[ $OFF != $POS ]]; then
			echo -e "\tuint8_t _rsvd_${POS}[$(( OFF-POS ))];"
		fi
		if grep -q "$NAME" < tscadcss_bitfields.h; then
			echo -e "\ttscadcss_${NAME}_reg_t $NAME;"
		else 
			echo -e "\tuint32_t $NAME;"
		fi
		POS=$((OFF+4));
	done
	echo "};"
	echo ""
	echo "#endif"
) > tscadcss.h

# Test function code
(
	echo "// This file is automatically generated by aux/INTC_REGS.sh"
	echo "#ifndef LHARTMANN_TSCADCSS_OFFSET_TEST_H"
	echo "#define LHARTMANN_TSCADCSS_OFFSET_TEST_H"
	echo ""
	echo "#include \"tscadcss.h\""
	echo ""
	echo '#define fail(XXX) { \'
	echo '	cerr << hex << "Failed offset for " #XXX ". Expected 0x" << TSCADCSS_OFFSET_##XXX << ", got 0x" << ((uint8_t*)&tscadc. XXX - (uint8_t*)&tscadc) << "." << endl << dec; \'
	echo '}'

	echo "bool test_tscadc_offsets() {"
	echo -e "\ttscadcss_regs_t intc;"
	echo -e "\t bool err = false;"
	echo "$REGLIST" | while read ADDR NAME; do
		echo -e "\tif ((uint8_t*)&tscadc.$NAME - (uint8_t*)&tscadc != TSCADCSS_OFFSET_$NAME) {"
		echo -e "\t\tfail($NAME);"
		echo -e "\t\terr = true;"
		echo -e "\t}"
	done
	echo -e "\treturn err;"
	echo "}"
	echo ""
	echo "#endif"
) > tscadcss_test.h
