// This file is automatically generated by tools/coding_assist/DMTIMER.sh
#ifndef LHARTMANN_DMTIMER_H
#define LHARTMANN_DMTIMER_H

#include <BBB/dmtimer_structs.h>

extern volatile far struct dmtimer_regs_t DMTimer0Regs;
extern volatile far struct dmtimer_regs_t DMTimer1Regs;
extern volatile far struct dmtimer_regs_t DMTimer2Regs;
extern volatile far struct dmtimer_regs_t DMTimer3Regs;
extern volatile far struct dmtimer_regs_t DMTimer4Regs;
extern volatile far struct dmtimer_regs_t DMTimer5Regs;
extern volatile far struct dmtimer_regs_t DMTimer6Regs;
extern volatile far struct dmtimer_regs_t DMTimer7Regs;

#endif
