/* This file is automatically generated by tools/coding_assist/DMTIMER.sh */
MEMORY {
	PAGE 1: /* Data memory */
	DMTIMER0 : origin = 0x44E05000, length = 92
	DMTIMER1 : origin = 0x44E31000, length = 92
	DMTIMER2 : origin = 0x48040000, length = 92
	DMTIMER3 : origin = 0x48042000, length = 92
	DMTIMER4 : origin = 0x48044000, length = 92
	DMTIMER5 : origin = 0x48046000, length = 92
	DMTIMER6 : origin = 0x48048000, length = 92
	DMTIMER7 : origin = 0x4804A000, length = 92
}
SECTIONS {
	DMTimer0RegsFile : > DMTIMER0, PAGE = 1
	DMTimer1RegsFile : > DMTIMER1, PAGE = 1
	DMTimer2RegsFile : > DMTIMER2, PAGE = 1
	DMTimer3RegsFile : > DMTIMER3, PAGE = 1
	DMTimer4RegsFile : > DMTIMER4, PAGE = 1
	DMTimer5RegsFile : > DMTIMER5, PAGE = 1
	DMTimer6RegsFile : > DMTIMER6, PAGE = 1
	DMTimer7RegsFile : > DMTIMER7, PAGE = 1
}
