// This file is automatically generated by tools/coding_assist/DMTIMER.sh
//----------------------------------------
#include <dmtimer.h>
//----------------------------------------

#ifdef __cplusplus
#pragma DATA_SECTION("DMTimer0RegsFile")
#else
#pragma DATA_SECTION(DMTimer0Regs,"DMTimer0RegsFile");
#endif
volatile struct dmtimer_regs_t DMTimer0Regs;

#ifdef __cplusplus
#pragma DATA_SECTION("DMTimer1RegsFile")
#else
#pragma DATA_SECTION(DMTimer1Regs,"DMTimer1RegsFile");
#endif
volatile struct dmtimer_regs_t DMTimer1Regs;

#ifdef __cplusplus
#pragma DATA_SECTION("DMTimer2RegsFile")
#else
#pragma DATA_SECTION(DMTimer2Regs,"DMTimer2RegsFile");
#endif
volatile struct dmtimer_regs_t DMTimer2Regs;

#ifdef __cplusplus
#pragma DATA_SECTION("DMTimer3RegsFile")
#else
#pragma DATA_SECTION(DMTimer3Regs,"DMTimer3RegsFile");
#endif
volatile struct dmtimer_regs_t DMTimer3Regs;

#ifdef __cplusplus
#pragma DATA_SECTION("DMTimer4RegsFile")
#else
#pragma DATA_SECTION(DMTimer4Regs,"DMTimer4RegsFile");
#endif
volatile struct dmtimer_regs_t DMTimer4Regs;

#ifdef __cplusplus
#pragma DATA_SECTION("DMTimer5RegsFile")
#else
#pragma DATA_SECTION(DMTimer5Regs,"DMTimer5RegsFile");
#endif
volatile struct dmtimer_regs_t DMTimer5Regs;

#ifdef __cplusplus
#pragma DATA_SECTION("DMTimer6RegsFile")
#else
#pragma DATA_SECTION(DMTimer6Regs,"DMTimer6RegsFile");
#endif
volatile struct dmtimer_regs_t DMTimer6Regs;

#ifdef __cplusplus
#pragma DATA_SECTION("DMTimer7RegsFile")
#else
#pragma DATA_SECTION(DMTimer7Regs,"DMTimer7RegsFile");
#endif
volatile struct dmtimer_regs_t DMTimer7Regs;

//----------------------------------------
