// This file is automatically generated by aux/PWMSS_REGS.sh
#ifndef FILIPEBELO_PWMSS_OFFSET_TEST_H
#define FILIPEBELO_PWMSS_OFFSET_TEST_H

#include "pwmss.h"

#define fail(XXX) { \
	cerr << hex << "Failed offset for " #XXX ". Expected 0x" << PWMSS_OFFSET_##XXX << ", got 0x" << ((uint8_t*)&pwm. XXX - (uint8_t*)&pwm) << "." << endl << dec; \
}
bool test_pwmss_offsets() {
	pwmss_regs_t pwm;
	 bool err = false;
	if ((uint8_t*)&pwm.IDVER - (uint8_t*)&pwm != PWMSS_OFFSET_IDVER) {
		fail(IDVER);
		err = true;
	}
	if ((uint8_t*)&pwm.SYSCONFIG - (uint8_t*)&pwm != PWMSS_OFFSET_SYSCONFIG) {
		fail(SYSCONFIG);
		err = true;
	}
	if ((uint8_t*)&pwm.CLKCONFIG - (uint8_t*)&pwm != PWMSS_OFFSET_CLKCONFIG) {
		fail(CLKCONFIG);
		err = true;
	}
	if ((uint8_t*)&pwm.CLKSTATUS - (uint8_t*)&pwm != PWMSS_OFFSET_CLKSTATUS) {
		fail(CLKSTATUS);
		err = true;
	}
	return err;
}
#undef fail

#endif
